import { createContext, type ReactNode, useContext, useEffect, useMemo } from "react";
import type { TravelMode, TripLanguage } from "./model";

const english = {
  loadingTrip: "Loading trip",
  syncUnavailable: "Sync server is unavailable",
  connectingPlan: "Connecting to the shared plan",
  placeFallback: "Place",
  deleteDayBlocked: "Move or delete reservations before deleting this day.",
  tripDatesBlocked: "Move or delete reservations outside the new trip dates.",
  tripTitle: "Trip title",
  allSynced: "All changes synced",
  saving: "Saving changes",
  connecting: "Connecting",
  offline: "Offline",
  editorsOnline: "{count} editors online",
  undo: "Undo",
  redo: "Redo",
  tripSettings: "Trip settings",
  deleteTrip: "Delete trip",
  share: "Share",
  tripDates: "Trip dates",
  placesToVisit: "Places to visit",
  plannerView: "Planner view",
  list: "List",
  map: "Map",
  itinerary: "Itinerary",
  calendar: "Calendar",
  noLodging: "No lodging",
  addPlace: "Add a place",
  addReservation: "Add reservation",
  addLodging: "Add lodging",
  addTransport: "Add transport",
  calendarAddPlace: "Add place",
  previousDay: "Previous day",
  nextDay: "Next day",
  addDayBefore: "Add a day before {date}",
  addDayAfter: "Add a day after {date}",
  earlier15: "15 minutes earlier",
  later15: "15 minutes later",
  longer15: "15 minutes longer",
  shorter15: "15 minutes shorter",
  duplicate: "Duplicate",
  delete: "Delete",
  noItems: "No items for this day",
  tripCalendar: "Trip calendar",
  allDay: "All day",
  day: "day",
  days: "days",
  continued: "Continued",
  flexible: "Flexible",
  makeFlexible: "Make flexible",
  changeCheckIn: "Change check-in for {title}",
  changeCheckOut: "Change check-out for {title}",
  changeStart: "Change start of {title}",
  changeEnd: "Change end of {title}",
  calendarActions: "Calendar actions for {title}",
  calendarAddItem: "Add calendar item",
  conflict: "conflict",
  displayNameTitle: "Please tell us your name",
  displayNameBody: "Other people in this trip can see your name and presence color.",
  yourName: "Your name",
  continue: "Continue",
  cancel: "Cancel",
  shareTitle: "Anyone with this link can edit",
  shareBody:
    "The trip has no account or access control. Share the full URL only with people who may change or delete the trip.",
  copyLink: "Copy link",
  deleteTripTitle: "Delete this trip?",
  deleteTripBody:
    "This disconnects every editor and permanently deletes server data. Type {title} to continue.",
  tripTitleConfirmation: "Trip title confirmation",
  showItinerary: "Show itinerary",
  hideItinerary: "Hide itinerary",
  hideItineraryResize: "Hide itinerary. Drag or use arrow keys to resize.",
  start: "Start",
  end: "End",
  confirmed: "Confirmed",
  moveUp: "Move {title} up",
  moveDown: "Move {title} down",
  deleteItem: "Delete {title}",
  updatingRoute: "Updating route",
  stale: "Stale",
  routeUnavailable: "Route unavailable",
  travelMode: "Travel mode",
  openLegGoogleMaps: "Open this route in Google Maps",
  openDayGoogleMaps: "Open this day in Google Maps",
  showDayRouteOnMap: "Show {date} route on map",
  dayRouteFewPlaces: "Add at least two places to export this day",
  dayRouteGap: "Connect every place to export this day",
  dayRouteMixedModes: "Use one travel mode to export this day",
  dayRouteUnavailable: "Wait until every route is available",
  deleteDay: "Delete day {date}",
  deleteDayConfirm: "Delete this day? {count} items will move to Places to visit.",
  moreItemTypes: "More item types for {date}",
  addItemToDay: "Add item to {date}",
  place: "Place",
  note: "Note",
  reservation: "Reservation",
  lodging: "Lodging",
  transport: "Transport",
  addType: "Add {type}",
  uiLanguage: "UI language",
  tripLanguage: "Trip language",
  followUiLanguage: "Follow UI language ({language})",
  distanceUnits: "Distance units",
  metricUnits: "Metric",
  imperialUnits: "Imperial",
  defaultTransport: "Default transportation",
  calendarDayStart: "Calendar day starts",
  saveSettings: "Save settings",
  discardTripSettings: "Discard unsaved trip settings?",
  date: "Date",
  startTime: "Start time",
  leaveAt: "Leave at",
  stayAt: "Stay at {title}",
  checkInDate: "Check-in date",
  checkOutDate: "Check-out date",
  searchGooglePlaces: "Search Google Places",
  checkingPlacement: "Checking placement and saving...",
  choosePlace: "Choose a place",
  chooseDateTime: "Choose a date and time",
  checkoutAfterCheckin: "Check-out must be after check-in",
  couldNotAddPlace: "Could not add this place",
  googlePlacesUnavailable: "Google Places is unavailable",
  couldNotLoadGooglePlace: "Could not load this Google place",
  somePlacesUnavailable: "Some Google place locations are unavailable",
  placeDetails: "Place details",
  removeFromDay: "Remove from day {day}",
  addToTrip: "Add to trip",
  closePlaceDetails: "Close place details",
  loadingPlaceDetails: "Loading place details...",
  placeDetailsUnavailable: "Google place details are unavailable.",
  retry: "Retry",
  tripMap: "Trip map",
  mapUnavailable: "Map unavailable",
  transportLocationsUnavailable: "Transport locations are unavailable",
  stopLabel: "Stop {index}: {label}",
  selectedPlace: "Selected place",
  changeField: "Change {field}",
  removeField: "Remove {field}",
  keepField: "Keep {field}",
  itineraryLabel: "Itinerary label",
  editLabel: "Edit {title} label",
  changeToReservation: "Change to reservation",
  changeToReservationConfirm: "Change this place to a reservation?",
  closeEditor: "Close editor",
  travelMethod: "Travel method",
  customTravelMethod: "Custom travel method",
  from: "From",
  to: "To",
  departureTime: "Departure time",
  arrivalTime: "Arrival time",
  durationMinutes: "Duration in minutes",
  notes: "Notes",
  markdownSupported: "Markdown supported",
  edit: "Edit",
  preview: "Preview",
  stayAfterCheckin: "Check-out must be after check-in.",
  stayOverlap: "The stay must overlap the trip dates.",
  choosePlaceSaving: "Choose a place before saving.",
  scheduleReservation: "Schedule this reservation on a day before saving.",
  chooseStartSaving: "Choose a start time before saving.",
  chooseArrival: "Choose an arrival time.",
  provider: "Provider",
  confirmation: "Confirmation",
  arrivalDate: "Arrival date",
  departureDate: "Departure date",
  plane: "Plane",
  train: "Train",
  bus: "Bus",
  ferry: "Ferry",
  custom: "Custom",
  car: "Car",
  publicTransport: "Public transport",
  walk: "Walk",
  transportOrigin: "Transport origin",
  transportDestination: "Transport destination",
  loadingEditor: "Loading editor",
  nothingToPreview: "Nothing to preview.",
  home: "PaceNotes home",
  tripTo: "Trip to {place}",
  invalidLocalTime: "This local time is missing or ambiguous because of a clock change.",
  overlapsItem: "Overlaps {title}.",
  travelCannotFinish: "Travel from {title} cannot finish before this start time.",
} as const;

type TripTextKey = keyof typeof english;
type TripText = (key: TripTextKey, values?: Record<string, string | number>) => string;

type TranslationTable = { en: Partial<Record<TripTextKey, string>> } & Record<
  Exclude<TripLanguage, "en">,
  Record<TripTextKey, string>
>;

const translations: TranslationTable = {
  en: {},
  de: {
    loadingTrip: "Reise wird geladen",
    syncUnavailable: "Synchronisierungsserver ist nicht verfügbar",
    connectingPlan: "Verbindung zum gemeinsamen Plan wird hergestellt",
    placeFallback: "Ort",
    deleteDayBlocked: "Verschieben oder löschen Sie Reservierungen, bevor Sie diesen Tag löschen.",
    tripDatesBlocked: "Verschieben oder löschen Sie Reservierungen außerhalb der neuen Reisedaten.",
    tripTitle: "Reisetitel",
    allSynced: "Alle Änderungen synchronisiert",
    saving: "Änderungen werden gespeichert",
    connecting: "Verbindung wird hergestellt",
    offline: "Offline",
    editorsOnline: "{count} Personen online",
    undo: "Rückgängig",
    redo: "Wiederholen",
    tripSettings: "Reiseeinstellungen",
    deleteTrip: "Reise löschen",
    share: "Teilen",
    tripDates: "Reisedaten",
    placesToVisit: "Orte zum Besuchen",
    plannerView: "Planeransicht",
    list: "Liste",
    map: "Karte",
    itinerary: "Reiseplan",
    noLodging: "Keine Unterkunft",
    addPlace: "Ort hinzufügen",
    addReservation: "Reservierung hinzufügen",
    addLodging: "Unterkunft hinzufügen",
    calendar: "Kalender",
    addTransport: "Transport hinzufügen",
    calendarAddPlace: "Ort hinzufügen",
    previousDay: "Vorheriger Tag",
    nextDay: "Nächster Tag",
    addDayBefore: "Tag vor {date} hinzufügen",
    addDayAfter: "Tag nach {date} hinzufügen",
    earlier15: "15 Minuten früher",
    later15: "15 Minuten später",
    longer15: "15 Minuten länger",
    shorter15: "15 Minuten kürzer",
    duplicate: "Duplizieren",
    delete: "Löschen",
    tripCalendar: "Reisekalender",
    allDay: "Ganztägig",
    day: "Tag",
    days: "Tage",
    continued: "Fortgesetzt",
    flexible: "Flexibel",
    makeFlexible: "Flexibel machen",
    changeCheckIn: "Check-in von {title} ändern",
    changeCheckOut: "Check-out von {title} ändern",
    changeStart: "Beginn von {title} ändern",
    changeEnd: "Ende von {title} ändern",
    calendarActions: "Kalenderaktionen für {title}",
    calendarAddItem: "Kalendereintrag hinzufügen",
    conflict: "Konflikt",
    noItems: "Keine Einträge für diesen Tag",
    displayNameTitle: "Bitte nennen Sie uns Ihren Namen",
    displayNameBody:
      "Andere Personen dieser Reise können Ihren Namen und Ihre Anwesenheitsfarbe sehen.",
    yourName: "Ihr Name",
    continue: "Weiter",
    cancel: "Abbrechen",
    shareTitle: "Jeder mit diesem Link kann bearbeiten",
    shareBody:
      "Die Reise hat kein Konto und keine Zugriffskontrolle. Teilen Sie die vollständige URL nur mit Personen, die die Reise ändern oder löschen dürfen.",
    copyLink: "Link kopieren",
    deleteTripTitle: "Diese Reise löschen?",
    deleteTripBody:
      "Dadurch werden alle Personen getrennt und die Serverdaten dauerhaft gelöscht. Geben Sie {title} ein, um fortzufahren.",
    tripTitleConfirmation: "Bestätigung des Reisetitels",
    showItinerary: "Reiseplan anzeigen",
    hideItinerary: "Reiseplan ausblenden",
    hideItineraryResize:
      "Reiseplan ausblenden. Ziehen oder Pfeiltasten zum Ändern der Größe verwenden.",
    start: "Start",
    end: "Ende",
    confirmed: "Bestätigt",
    moveUp: "{title} nach oben verschieben",
    moveDown: "{title} nach unten verschieben",
    deleteItem: "{title} löschen",
    updatingRoute: "Route wird aktualisiert",
    stale: "Veraltet",
    routeUnavailable: "Route nicht verfügbar",
    travelMode: "Verkehrsmittel",
    openLegGoogleMaps: "Diese Route in Google Maps öffnen",
    openDayGoogleMaps: "Diesen Tag in Google Maps öffnen",
    showDayRouteOnMap: "Route für {date} auf der Karte anzeigen",
    dayRouteFewPlaces: "Fügen Sie mindestens zwei Orte hinzu, um diesen Tag zu exportieren",
    dayRouteGap: "Verbinden Sie alle Orte, um diesen Tag zu exportieren",
    dayRouteMixedModes: "Verwenden Sie ein Verkehrsmittel, um diesen Tag zu exportieren",
    dayRouteUnavailable: "Warten Sie, bis alle Routen verfügbar sind",
    deleteDay: "Tag {date} löschen",
    moreItemTypes: "Weitere Eintragstypen für {date}",
    addItemToDay: "Eintrag zu {date} hinzufügen",
    place: "Ort",
    note: "Notiz",
    reservation: "Reservierung",
    lodging: "Unterkunft",
    transport: "Transport",
    addType: "{type} hinzufügen",
    uiLanguage: "Sprache der Benutzeroberfläche",
    tripLanguage: "Reisesprache",
    followUiLanguage: "Sprache der Benutzeroberfläche verwenden ({language})",
    distanceUnits: "Entfernungseinheiten",
    metricUnits: "Metrisch",
    imperialUnits: "Imperial",
    defaultTransport: "Standardverkehrsmittel",
    calendarDayStart: "Beginn des Kalendertags",
    saveSettings: "Einstellungen speichern",
    discardTripSettings: "Nicht gespeicherte Reiseeinstellungen verwerfen?",
    date: "Datum",
    startTime: "Startzeit",
    leaveAt: "Abreise um",
    stayAt: "Aufenthalt in {title}",
    checkInDate: "Anreisedatum",
    checkOutDate: "Abreisedatum",
    searchGooglePlaces: "Google Places durchsuchen",
    checkingPlacement: "Platzierung wird geprüft und gespeichert...",
    choosePlace: "Wählen Sie einen Ort",
    chooseDateTime: "Wählen Sie Datum und Uhrzeit",
    checkoutAfterCheckin: "Abreise muss nach der Anreise liegen",
    couldNotAddPlace: "Dieser Ort konnte nicht hinzugefügt werden",
    googlePlacesUnavailable: "Google Places ist nicht verfügbar",
    couldNotLoadGooglePlace: "Dieser Google-Ort konnte nicht geladen werden",
    somePlacesUnavailable: "Einige Google-Orte sind nicht verfügbar",
    placeDetails: "Ortsdetails",
    removeFromDay: "Aus Tag {day} entfernen",
    addToTrip: "Zur Reise hinzufügen",
    closePlaceDetails: "Ortsdetails schließen",
    loadingPlaceDetails: "Ortsdetails werden geladen...",
    placeDetailsUnavailable: "Google-Ortsdetails sind nicht verfügbar.",
    retry: "Erneut versuchen",
    tripMap: "Reisekarte",
    mapUnavailable: "Karte nicht verfügbar",
    transportLocationsUnavailable: "Transportorte sind nicht verfügbar",
    stopLabel: "Stopp {index}: {label}",
    selectedPlace: "Ausgewählter Ort",
    changeField: "{field} ändern",
    removeField: "{field} entfernen",
    keepField: "{field} behalten",
    itineraryLabel: "Reiseplanbezeichnung",
    editLabel: "Bezeichnung von {title} bearbeiten",
    changeToReservation: "In Reservierung ändern",
    changeToReservationConfirm: "Diesen Ort in eine Reservierung ändern?",
    closeEditor: "Editor schließen",
    travelMethod: "Reiseart",
    customTravelMethod: "Benutzerdefinierte Reiseart",
    from: "Von",
    to: "Nach",
    departureTime: "Abfahrtszeit",
    arrivalTime: "Ankunftszeit",
    durationMinutes: "Dauer in Minuten",
    notes: "Notizen",
    markdownSupported: "Markdown unterstützt",
    edit: "Bearbeiten",
    preview: "Vorschau",
    stayAfterCheckin: "Abreise muss nach der Anreise liegen.",
    stayOverlap: "Der Aufenthalt muss die Reisedaten überschneiden.",
    choosePlaceSaving: "Wählen Sie vor dem Speichern einen Ort.",
    scheduleReservation: "Planen Sie diese Reservierung vor dem Speichern für einen Tag.",
    chooseStartSaving: "Wählen Sie vor dem Speichern eine Startzeit.",
    chooseArrival: "Wählen Sie eine Ankunftszeit.",
    provider: "Anbieter",
    confirmation: "Bestätigung",
    arrivalDate: "Anreisedatum",
    departureDate: "Abreisedatum",
    plane: "Flugzeug",
    train: "Zug",
    bus: "Bus",
    ferry: "Fähre",
    custom: "Benutzerdefiniert",
    car: "Auto",
    publicTransport: "Öffentliche Verkehrsmittel",
    walk: "Zu Fuß",
    transportOrigin: "Transportstart",
    transportDestination: "Transportziel",
    deleteDayConfirm:
      "Diesen Tag löschen? {count} Einträge werden zu „Orte zum Besuchen“ verschoben.",
    loadingEditor: "Editor wird geladen",
    nothingToPreview: "Keine Vorschau verfügbar.",
    home: "PaceNotes-Startseite",
    tripTo: "Reise nach {place}",
    invalidLocalTime: "Diese Ortszeit fehlt oder ist wegen einer Zeitumstellung mehrdeutig.",
    overlapsItem: "Überschneidet sich mit {title}.",
    travelCannotFinish: "Die Fahrt von {title} kann nicht vor dieser Startzeit enden.",
  },
  es: {
    loadingTrip: "Cargando viaje",
    syncUnavailable: "El servidor de sincronización no está disponible",
    connectingPlan: "Conectando con el plan compartido",
    placeFallback: "Lugar",
    deleteDayBlocked: "Mueve o elimina las reservas antes de eliminar este día.",
    tripDatesBlocked:
      "Mueve o elimina las reservas que estén fuera de las nuevas fechas del viaje.",
    tripTitle: "Título del viaje",
    allSynced: "Todos los cambios sincronizados",
    saving: "Guardando cambios",
    connecting: "Conectando",
    offline: "Sin conexión",
    editorsOnline: "{count} personas en línea",
    undo: "Deshacer",
    redo: "Rehacer",
    tripSettings: "Ajustes del viaje",
    deleteTrip: "Eliminar viaje",
    share: "Compartir",
    tripDates: "Fechas del viaje",
    placesToVisit: "Lugares para visitar",
    plannerView: "Vista del planificador",
    list: "Lista",
    map: "Mapa",
    itinerary: "Itinerario",
    noLodging: "Sin alojamiento",
    addPlace: "Añadir un lugar",
    addReservation: "Añadir reserva",
    addLodging: "Añadir alojamiento",
    calendar: "Calendario",
    addTransport: "Añadir transporte",
    calendarAddPlace: "Añadir lugar",
    previousDay: "Día anterior",
    nextDay: "Día siguiente",
    addDayBefore: "Añadir un día antes de {date}",
    addDayAfter: "Añadir un día después de {date}",
    earlier15: "15 minutos antes",
    later15: "15 minutos después",
    longer15: "15 minutos más",
    shorter15: "15 minutos menos",
    duplicate: "Duplicar",
    delete: "Eliminar",
    tripCalendar: "Calendario del viaje",
    allDay: "Todo el día",
    day: "día",
    days: "días",
    continued: "Continuación",
    flexible: "Flexible",
    makeFlexible: "Hacer flexible",
    changeCheckIn: "Cambiar la entrada de {title}",
    changeCheckOut: "Cambiar la salida de {title}",
    changeStart: "Cambiar el inicio de {title}",
    changeEnd: "Cambiar el final de {title}",
    calendarActions: "Acciones del calendario para {title}",
    calendarAddItem: "Añadir elemento al calendario",
    conflict: "conflicto",
    noItems: "No hay elementos para este día",
    displayNameTitle: "Dinos tu nombre",
    displayNameBody: "Las otras personas de este viaje pueden ver tu nombre y color de presencia.",
    yourName: "Tu nombre",
    continue: "Continuar",
    cancel: "Cancelar",
    shareTitle: "Cualquier persona con este enlace puede editar",
    shareBody:
      "El viaje no tiene cuenta ni control de acceso. Comparte la URL completa solo con personas que puedan cambiar o eliminar el viaje.",
    copyLink: "Copiar enlace",
    deleteTripTitle: "¿Eliminar este viaje?",
    deleteTripBody:
      "Esto desconecta a todas las personas y elimina permanentemente los datos del servidor. Escribe {title} para continuar.",
    tripTitleConfirmation: "Confirmación del título del viaje",
    showItinerary: "Mostrar itinerario",
    hideItinerary: "Ocultar itinerario",
    hideItineraryResize: "Ocultar itinerario. Arrastra o usa las flechas para cambiar el tamaño.",
    start: "Inicio",
    end: "Fin",
    confirmed: "Confirmado",
    moveUp: "Mover {title} arriba",
    moveDown: "Mover {title} abajo",
    deleteItem: "Eliminar {title}",
    updatingRoute: "Actualizando ruta",
    stale: "Desactualizada",
    routeUnavailable: "Ruta no disponible",
    travelMode: "Modo de viaje",
    openLegGoogleMaps: "Abrir esta ruta en Google Maps",
    openDayGoogleMaps: "Abrir este día en Google Maps",
    showDayRouteOnMap: "Mostrar la ruta del {date} en el mapa",
    dayRouteFewPlaces: "Añade al menos dos lugares para exportar este día",
    dayRouteGap: "Conecta todos los lugares para exportar este día",
    dayRouteMixedModes: "Usa un solo modo de viaje para exportar este día",
    dayRouteUnavailable: "Espera hasta que todas las rutas estén disponibles",
    deleteDay: "Eliminar el día {date}",
    moreItemTypes: "Más tipos de elemento para {date}",
    addItemToDay: "Añadir elemento a {date}",
    place: "Lugar",
    note: "Nota",
    reservation: "Reserva",
    lodging: "Alojamiento",
    transport: "Transporte",
    addType: "Añadir {type}",
    uiLanguage: "Idioma de la interfaz",
    tripLanguage: "Idioma del viaje",
    followUiLanguage: "Usar el idioma de la interfaz ({language})",
    distanceUnits: "Unidades de distancia",
    metricUnits: "Métrico",
    imperialUnits: "Imperial",
    defaultTransport: "Transporte predeterminado",
    calendarDayStart: "Inicio del día del calendario",
    saveSettings: "Guardar ajustes",
    discardTripSettings: "¿Descartar los ajustes del viaje sin guardar?",
    date: "Fecha",
    startTime: "Hora de inicio",
    leaveAt: "Salida a las",
    stayAt: "Estancia en {title}",
    checkInDate: "Fecha de entrada",
    checkOutDate: "Fecha de salida",
    searchGooglePlaces: "Buscar en Google Places",
    checkingPlacement: "Comprobando ubicación y guardando...",
    choosePlace: "Elige un lugar",
    chooseDateTime: "Elige una fecha y hora",
    checkoutAfterCheckin: "La salida debe ser posterior a la entrada",
    couldNotAddPlace: "No se pudo añadir este lugar",
    googlePlacesUnavailable: "Google Places no está disponible",
    couldNotLoadGooglePlace: "No se pudo cargar este lugar de Google",
    somePlacesUnavailable: "Algunos lugares de Google no están disponibles",
    placeDetails: "Detalles del lugar",
    removeFromDay: "Quitar del día {day}",
    addToTrip: "Añadir al viaje",
    closePlaceDetails: "Cerrar detalles del lugar",
    loadingPlaceDetails: "Cargando detalles del lugar...",
    placeDetailsUnavailable: "Los detalles del lugar de Google no están disponibles.",
    retry: "Reintentar",
    tripMap: "Mapa del viaje",
    mapUnavailable: "Mapa no disponible",
    transportLocationsUnavailable: "Las ubicaciones de transporte no están disponibles",
    stopLabel: "Parada {index}: {label}",
    selectedPlace: "Lugar seleccionado",
    changeField: "Cambiar {field}",
    removeField: "Quitar {field}",
    keepField: "Mantener {field}",
    itineraryLabel: "Etiqueta del itinerario",
    editLabel: "Editar etiqueta de {title}",
    changeToReservation: "Cambiar a reserva",
    changeToReservationConfirm: "¿Cambiar este lugar a una reserva?",
    closeEditor: "Cerrar editor",
    travelMethod: "Método de viaje",
    customTravelMethod: "Método de viaje personalizado",
    from: "Desde",
    to: "Hasta",
    departureTime: "Hora de salida",
    arrivalTime: "Hora de llegada",
    durationMinutes: "Duración en minutos",
    notes: "Notas",
    markdownSupported: "Compatible con Markdown",
    edit: "Editar",
    preview: "Vista previa",
    stayAfterCheckin: "La salida debe ser posterior a la entrada.",
    stayOverlap: "La estancia debe coincidir con las fechas del viaje.",
    choosePlaceSaving: "Elige un lugar antes de guardar.",
    scheduleReservation: "Programa esta reserva en un día antes de guardar.",
    chooseStartSaving: "Elige una hora de inicio antes de guardar.",
    chooseArrival: "Elige una hora de llegada.",
    provider: "Proveedor",
    confirmation: "Confirmación",
    arrivalDate: "Fecha de llegada",
    departureDate: "Fecha de salida",
    plane: "Avión",
    train: "Tren",
    bus: "Autobús",
    ferry: "Ferri",
    custom: "Personalizado",
    car: "Coche",
    publicTransport: "Transporte público",
    walk: "A pie",
    transportOrigin: "Origen del transporte",
    transportDestination: "Destino del transporte",
    deleteDayConfirm: "¿Eliminar este día? {count} elementos se moverán a Lugares para visitar.",
    loadingEditor: "Cargando editor",
    nothingToPreview: "No hay nada que previsualizar.",
    home: "Inicio de PaceNotes",
    tripTo: "Viaje a {place}",
    invalidLocalTime: "Esta hora local no existe o es ambigua debido a un cambio de reloj.",
    overlapsItem: "Se solapa con {title}.",
    travelCannotFinish: "El trayecto desde {title} no puede terminar antes de esta hora de inicio.",
  },
  fr: {
    loadingTrip: "Chargement du voyage",
    syncUnavailable: "Le serveur de synchronisation est indisponible",
    connectingPlan: "Connexion au programme partagé",
    placeFallback: "Lieu",
    deleteDayBlocked: "Déplacez ou supprimez les réservations avant de supprimer ce jour.",
    tripDatesBlocked:
      "Déplacez ou supprimez les réservations qui se trouvent hors des nouvelles dates.",
    tripTitle: "Titre du voyage",
    allSynced: "Toutes les modifications sont synchronisées",
    saving: "Enregistrement des modifications",
    connecting: "Connexion",
    offline: "Hors ligne",
    editorsOnline: "{count} personnes en ligne",
    undo: "Annuler",
    redo: "Rétablir",
    tripSettings: "Paramètres du voyage",
    deleteTrip: "Supprimer le voyage",
    share: "Partager",
    tripDates: "Dates du voyage",
    placesToVisit: "Lieux à visiter",
    plannerView: "Vue du planificateur",
    list: "Liste",
    map: "Carte",
    itinerary: "Itinéraire",
    noLodging: "Aucun hébergement",
    addPlace: "Ajouter un lieu",
    addReservation: "Ajouter une réservation",
    addLodging: "Ajouter un hébergement",
    calendar: "Calendrier",
    addTransport: "Ajouter un transport",
    calendarAddPlace: "Ajouter un lieu",
    previousDay: "Jour précédent",
    nextDay: "Jour suivant",
    addDayBefore: "Ajouter un jour avant le {date}",
    addDayAfter: "Ajouter un jour après le {date}",
    earlier15: "15 minutes plus tôt",
    later15: "15 minutes plus tard",
    longer15: "15 minutes de plus",
    shorter15: "15 minutes de moins",
    duplicate: "Dupliquer",
    delete: "Supprimer",
    tripCalendar: "Calendrier du voyage",
    allDay: "Toute la journée",
    day: "jour",
    days: "jours",
    continued: "Suite",
    flexible: "Flexible",
    makeFlexible: "Rendre flexible",
    changeCheckIn: "Modifier l'arrivée de {title}",
    changeCheckOut: "Modifier le départ de {title}",
    changeStart: "Modifier le début de {title}",
    changeEnd: "Modifier la fin de {title}",
    calendarActions: "Actions du calendrier pour {title}",
    calendarAddItem: "Ajouter un élément au calendrier",
    conflict: "conflit",
    noItems: "Aucun élément pour ce jour",
    displayNameTitle: "Indiquez votre nom",
    displayNameBody:
      "Les autres personnes de ce voyage peuvent voir votre nom et votre couleur de présence.",
    yourName: "Votre nom",
    continue: "Continuer",
    cancel: "Annuler",
    shareTitle: "Toute personne ayant ce lien peut modifier",
    shareBody:
      "Le voyage ne comporte aucun compte ni contrôle d'accès. Partagez l'URL complète uniquement avec les personnes autorisées à modifier ou supprimer le voyage.",
    copyLink: "Copier le lien",
    deleteTripTitle: "Supprimer ce voyage ?",
    deleteTripBody:
      "Cette action déconnecte tout le monde et supprime définitivement les données du serveur. Saisissez {title} pour continuer.",
    tripTitleConfirmation: "Confirmation du titre du voyage",
    showItinerary: "Afficher l'itinéraire",
    hideItinerary: "Masquer l'itinéraire",
    hideItineraryResize:
      "Masquer l'itinéraire. Faites glisser ou utilisez les flèches pour redimensionner.",
    start: "Début",
    end: "Fin",
    confirmed: "Confirmé",
    moveUp: "Déplacer {title} vers le haut",
    moveDown: "Déplacer {title} vers le bas",
    deleteItem: "Supprimer {title}",
    updatingRoute: "Mise à jour de l'itinéraire",
    stale: "Ancien",
    routeUnavailable: "Itinéraire indisponible",
    travelMode: "Mode de déplacement",
    openLegGoogleMaps: "Ouvrir cet itinéraire dans Google Maps",
    openDayGoogleMaps: "Ouvrir ce jour dans Google Maps",
    showDayRouteOnMap: "Afficher l’itinéraire du {date} sur la carte",
    dayRouteFewPlaces: "Ajoutez au moins deux lieux pour exporter ce jour",
    dayRouteGap: "Reliez tous les lieux pour exporter ce jour",
    dayRouteMixedModes: "Utilisez un seul mode de déplacement pour exporter ce jour",
    dayRouteUnavailable: "Attendez que tous les itinéraires soient disponibles",
    deleteDay: "Supprimer le jour {date}",
    moreItemTypes: "Plus de types d'élément pour {date}",
    addItemToDay: "Ajouter un élément à {date}",
    place: "Lieu",
    note: "Note",
    reservation: "Réservation",
    lodging: "Hébergement",
    transport: "Transport",
    addType: "Ajouter {type}",
    uiLanguage: "Langue de l’interface",
    tripLanguage: "Langue du voyage",
    followUiLanguage: "Utiliser la langue de l’interface ({language})",
    distanceUnits: "Unités de distance",
    metricUnits: "Métrique",
    imperialUnits: "Impérial",
    defaultTransport: "Transport par défaut",
    calendarDayStart: "Début du jour du calendrier",
    saveSettings: "Enregistrer les paramètres",
    discardTripSettings: "Ignorer les paramètres du voyage non enregistrés ?",
    date: "Date",
    startTime: "Heure de début",
    leaveAt: "Départ à",
    stayAt: "Séjour à {title}",
    checkInDate: "Date d'arrivée",
    checkOutDate: "Date de départ",
    searchGooglePlaces: "Rechercher dans Google Places",
    checkingPlacement: "Vérification du placement et enregistrement...",
    choosePlace: "Choisissez un lieu",
    chooseDateTime: "Choisissez une date et une heure",
    checkoutAfterCheckin: "Le départ doit suivre l'arrivée",
    couldNotAddPlace: "Impossible d'ajouter ce lieu",
    googlePlacesUnavailable: "Google Places est indisponible",
    couldNotLoadGooglePlace: "Impossible de charger ce lieu Google",
    somePlacesUnavailable: "Certains lieux Google sont indisponibles",
    placeDetails: "Détails du lieu",
    removeFromDay: "Retirer du jour {day}",
    addToTrip: "Ajouter au voyage",
    closePlaceDetails: "Fermer les détails du lieu",
    loadingPlaceDetails: "Chargement des détails du lieu...",
    placeDetailsUnavailable: "Les détails du lieu Google sont indisponibles.",
    retry: "Réessayer",
    tripMap: "Carte du voyage",
    mapUnavailable: "Carte indisponible",
    transportLocationsUnavailable: "Les lieux de transport sont indisponibles",
    stopLabel: "Étape {index} : {label}",
    selectedPlace: "Lieu sélectionné",
    changeField: "Modifier {field}",
    removeField: "Retirer {field}",
    keepField: "Conserver {field}",
    itineraryLabel: "Libellé de l'itinéraire",
    editLabel: "Modifier le libellé de {title}",
    changeToReservation: "Transformer en réservation",
    changeToReservationConfirm: "Transformer ce lieu en réservation ?",
    closeEditor: "Fermer l'éditeur",
    travelMethod: "Mode de voyage",
    customTravelMethod: "Mode de voyage personnalisé",
    from: "De",
    to: "À",
    departureTime: "Heure de départ",
    arrivalTime: "Heure d'arrivée",
    durationMinutes: "Durée en minutes",
    notes: "Notes",
    markdownSupported: "Markdown pris en charge",
    edit: "Modifier",
    preview: "Aperçu",
    stayAfterCheckin: "Le départ doit suivre l'arrivée.",
    stayOverlap: "Le séjour doit chevaucher les dates du voyage.",
    choosePlaceSaving: "Choisissez un lieu avant l'enregistrement.",
    scheduleReservation: "Planifiez cette réservation sur un jour avant l'enregistrement.",
    chooseStartSaving: "Choisissez une heure de début avant l'enregistrement.",
    chooseArrival: "Choisissez une heure d'arrivée.",
    provider: "Fournisseur",
    confirmation: "Confirmation",
    arrivalDate: "Date d'arrivée",
    departureDate: "Date de départ",
    plane: "Avion",
    train: "Train",
    bus: "Bus",
    ferry: "Ferry",
    custom: "Personnalisé",
    car: "Voiture",
    publicTransport: "Transports publics",
    walk: "Marche",
    transportOrigin: "Origine du transport",
    transportDestination: "Destination du transport",
    deleteDayConfirm: "Supprimer ce jour ? {count} éléments seront déplacés vers Lieux à visiter.",
    loadingEditor: "Chargement de l'éditeur",
    nothingToPreview: "Rien à prévisualiser.",
    home: "Accueil de PaceNotes",
    tripTo: "Voyage à {place}",
    invalidLocalTime: "Cette heure locale est absente ou ambiguë à cause d'un changement d'heure.",
    overlapsItem: "Chevauche {title}.",
    travelCannotFinish:
      "Le trajet depuis {title} ne peut pas se terminer avant cette heure de début.",
  },
  it: {
    loadingTrip: "Caricamento del viaggio",
    syncUnavailable: "Il server di sincronizzazione non è disponibile",
    connectingPlan: "Connessione al piano condiviso",
    placeFallback: "Luogo",
    deleteDayBlocked: "Sposta o elimina le prenotazioni prima di eliminare questo giorno.",
    tripDatesBlocked:
      "Sposta o elimina le prenotazioni che non rientrano nelle nuove date del viaggio.",
    tripTitle: "Titolo del viaggio",
    allSynced: "Tutte le modifiche sono sincronizzate",
    saving: "Salvataggio delle modifiche",
    connecting: "Connessione",
    offline: "Non in linea",
    editorsOnline: "{count} persone in linea",
    undo: "Annulla",
    redo: "Ripeti",
    tripSettings: "Impostazioni del viaggio",
    deleteTrip: "Elimina viaggio",
    share: "Condividi",
    tripDates: "Date del viaggio",
    placesToVisit: "Luoghi da visitare",
    plannerView: "Vista del pianificatore",
    list: "Elenco",
    map: "Mappa",
    itinerary: "Itinerario",
    noLodging: "Nessun alloggio",
    addPlace: "Aggiungi un luogo",
    addReservation: "Aggiungi prenotazione",
    addLodging: "Aggiungi alloggio",
    calendar: "Calendario",
    addTransport: "Aggiungi trasporto",
    calendarAddPlace: "Aggiungi luogo",
    previousDay: "Giorno precedente",
    nextDay: "Giorno successivo",
    addDayBefore: "Aggiungi un giorno prima del {date}",
    addDayAfter: "Aggiungi un giorno dopo il {date}",
    earlier15: "15 minuti prima",
    later15: "15 minuti dopo",
    longer15: "15 minuti in più",
    shorter15: "15 minuti in meno",
    duplicate: "Duplica",
    delete: "Elimina",
    tripCalendar: "Calendario del viaggio",
    allDay: "Tutto il giorno",
    day: "giorno",
    days: "giorni",
    continued: "Continua",
    flexible: "Flessibile",
    makeFlexible: "Rendi flessibile",
    changeCheckIn: "Modifica il check-in di {title}",
    changeCheckOut: "Modifica il check-out di {title}",
    changeStart: "Modifica l'inizio di {title}",
    changeEnd: "Modifica la fine di {title}",
    calendarActions: "Azioni del calendario per {title}",
    calendarAddItem: "Aggiungi elemento al calendario",
    conflict: "conflitto",
    noItems: "Nessun elemento per questo giorno",
    displayNameTitle: "Indica il tuo nome",
    displayNameBody:
      "Le altre persone del viaggio possono vedere il tuo nome e il colore di presenza.",
    yourName: "Il tuo nome",
    continue: "Continua",
    cancel: "Annulla",
    shareTitle: "Chiunque abbia questo link può modificare",
    shareBody:
      "Il viaggio non ha account o controllo degli accessi. Condividi l'URL completo solo con persone che possono modificare o eliminare il viaggio.",
    copyLink: "Copia link",
    deleteTripTitle: "Eliminare questo viaggio?",
    deleteTripBody:
      "Questa azione disconnette tutte le persone ed elimina definitivamente i dati del server. Digita {title} per continuare.",
    tripTitleConfirmation: "Conferma del titolo del viaggio",
    showItinerary: "Mostra itinerario",
    hideItinerary: "Nascondi itinerario",
    hideItineraryResize: "Nascondi itinerario. Trascina o usa i tasti freccia per ridimensionare.",
    start: "Inizio",
    end: "Fine",
    confirmed: "Confermato",
    moveUp: "Sposta {title} in alto",
    moveDown: "Sposta {title} in basso",
    deleteItem: "Elimina {title}",
    updatingRoute: "Aggiornamento del percorso",
    stale: "Non aggiornato",
    routeUnavailable: "Percorso non disponibile",
    travelMode: "Modalità di viaggio",
    openLegGoogleMaps: "Apri questo percorso in Google Maps",
    openDayGoogleMaps: "Apri questo giorno in Google Maps",
    showDayRouteOnMap: "Mostra l’itinerario del {date} sulla mappa",
    dayRouteFewPlaces: "Aggiungi almeno due luoghi per esportare questo giorno",
    dayRouteGap: "Collega tutti i luoghi per esportare questo giorno",
    dayRouteMixedModes: "Usa una sola modalità di viaggio per esportare questo giorno",
    dayRouteUnavailable: "Attendi che tutti i percorsi siano disponibili",
    deleteDay: "Elimina il giorno {date}",
    moreItemTypes: "Altri tipi di elemento per {date}",
    addItemToDay: "Aggiungi elemento a {date}",
    place: "Luogo",
    note: "Nota",
    reservation: "Prenotazione",
    lodging: "Alloggio",
    transport: "Trasporto",
    addType: "Aggiungi {type}",
    uiLanguage: "Lingua dell’interfaccia",
    tripLanguage: "Lingua del viaggio",
    followUiLanguage: "Usa la lingua dell’interfaccia ({language})",
    distanceUnits: "Unità di distanza",
    metricUnits: "Metrico",
    imperialUnits: "Imperiale",
    defaultTransport: "Trasporto predefinito",
    calendarDayStart: "Inizio del giorno del calendario",
    saveSettings: "Salva impostazioni",
    discardTripSettings: "Ignorare le impostazioni del viaggio non salvate?",
    date: "Data",
    startTime: "Ora di inizio",
    leaveAt: "Partenza alle",
    stayAt: "Soggiorno presso {title}",
    checkInDate: "Data di arrivo",
    checkOutDate: "Data di partenza",
    searchGooglePlaces: "Cerca in Google Places",
    checkingPlacement: "Controllo della posizione e salvataggio...",
    choosePlace: "Scegli un luogo",
    chooseDateTime: "Scegli una data e un'ora",
    checkoutAfterCheckin: "La partenza deve essere dopo l'arrivo",
    couldNotAddPlace: "Impossibile aggiungere questo luogo",
    googlePlacesUnavailable: "Google Places non è disponibile",
    couldNotLoadGooglePlace: "Impossibile caricare questo luogo Google",
    somePlacesUnavailable: "Alcuni luoghi Google non sono disponibili",
    placeDetails: "Dettagli del luogo",
    removeFromDay: "Rimuovi dal giorno {day}",
    addToTrip: "Aggiungi al viaggio",
    closePlaceDetails: "Chiudi i dettagli del luogo",
    loadingPlaceDetails: "Caricamento dei dettagli del luogo...",
    placeDetailsUnavailable: "I dettagli del luogo Google non sono disponibili.",
    retry: "Riprova",
    tripMap: "Mappa del viaggio",
    mapUnavailable: "Mappa non disponibile",
    transportLocationsUnavailable: "I luoghi di trasporto non sono disponibili",
    stopLabel: "Tappa {index}: {label}",
    selectedPlace: "Luogo selezionato",
    changeField: "Cambia {field}",
    removeField: "Rimuovi {field}",
    keepField: "Mantieni {field}",
    itineraryLabel: "Etichetta dell'itinerario",
    editLabel: "Modifica etichetta di {title}",
    changeToReservation: "Cambia in prenotazione",
    changeToReservationConfirm: "Cambiare questo luogo in una prenotazione?",
    closeEditor: "Chiudi editor",
    travelMethod: "Metodo di viaggio",
    customTravelMethod: "Metodo di viaggio personalizzato",
    from: "Da",
    to: "A",
    departureTime: "Ora di partenza",
    arrivalTime: "Ora di arrivo",
    durationMinutes: "Durata in minuti",
    notes: "Note",
    markdownSupported: "Markdown supportato",
    edit: "Modifica",
    preview: "Anteprima",
    stayAfterCheckin: "La partenza deve essere dopo l'arrivo.",
    stayOverlap: "Il soggiorno deve sovrapporsi alle date del viaggio.",
    choosePlaceSaving: "Scegli un luogo prima di salvare.",
    scheduleReservation: "Pianifica questa prenotazione in un giorno prima di salvare.",
    chooseStartSaving: "Scegli un'ora di inizio prima di salvare.",
    chooseArrival: "Scegli un'ora di arrivo.",
    provider: "Fornitore",
    confirmation: "Conferma",
    arrivalDate: "Data di arrivo",
    departureDate: "Data di partenza",
    plane: "Aereo",
    train: "Treno",
    bus: "Autobus",
    ferry: "Traghetto",
    custom: "Personalizzato",
    car: "Auto",
    publicTransport: "Trasporto pubblico",
    walk: "A piedi",
    transportOrigin: "Origine del trasporto",
    transportDestination: "Destinazione del trasporto",
    deleteDayConfirm:
      "Eliminare questo giorno? {count} elementi verranno spostati in Luoghi da visitare.",
    loadingEditor: "Caricamento dell'editor",
    nothingToPreview: "Niente da visualizzare in anteprima.",
    home: "Pagina iniziale di PaceNotes",
    tripTo: "Viaggio a {place}",
    invalidLocalTime: "Questa ora locale non esiste o è ambigua a causa di un cambio dell'ora.",
    overlapsItem: "Si sovrappone a {title}.",
    travelCannotFinish: "Il viaggio da {title} non può terminare prima di questo orario di inizio.",
  },
  ja: {
    loadingTrip: "旅行を読み込み中",
    syncUnavailable: "同期サーバーを利用できません",
    connectingPlan: "共有プランに接続中",
    placeFallback: "場所",
    deleteDayBlocked: "この日を削除する前に予約を移動または削除してください。",
    tripDatesBlocked: "新しい旅行日程の範囲外にある予約を移動または削除してください。",
    tripTitle: "旅行タイトル",
    allSynced: "すべての変更を同期しました",
    saving: "変更を保存中",
    connecting: "接続中",
    offline: "オフライン",
    editorsOnline: "{count}人がオンライン",
    undo: "元に戻す",
    redo: "やり直す",
    tripSettings: "旅行設定",
    deleteTrip: "旅行を削除",
    share: "共有",
    tripDates: "旅行日程",
    placesToVisit: "行きたい場所",
    plannerView: "プランナー表示",
    list: "リスト",
    map: "地図",
    itinerary: "旅程",
    noLodging: "宿泊先なし",
    addPlace: "場所を追加",
    addReservation: "予約を追加",
    addLodging: "宿泊先を追加",
    calendar: "カレンダー",
    addTransport: "移動を追加",
    calendarAddPlace: "場所を追加",
    previousDay: "前日",
    nextDay: "翌日",
    addDayBefore: "{date}の前に1日追加",
    addDayAfter: "{date}の後に1日追加",
    earlier15: "15分早く",
    later15: "15分遅く",
    longer15: "15分長く",
    shorter15: "15分短く",
    duplicate: "複製",
    delete: "削除",
    tripCalendar: "旅行カレンダー",
    allDay: "終日",
    day: "日",
    days: "日",
    continued: "続き",
    flexible: "フレキシブル",
    makeFlexible: "時間を自由にする",
    changeCheckIn: "{title}のチェックイン日を変更",
    changeCheckOut: "{title}のチェックアウト日を変更",
    changeStart: "{title}の開始時刻を変更",
    changeEnd: "{title}の終了時刻を変更",
    calendarActions: "{title}のカレンダー操作",
    calendarAddItem: "カレンダー項目を追加",
    conflict: "競合",
    noItems: "この日の項目はありません",
    displayNameTitle: "名前を入力してください",
    displayNameBody: "この旅行の他の参加者には、あなたの名前とプレゼンス色が表示されます。",
    yourName: "あなたの名前",
    continue: "続行",
    cancel: "キャンセル",
    shareTitle: "リンクを知っている人は編集できます",
    shareBody:
      "この旅行にはアカウントやアクセス制御がありません。旅行を変更または削除してよい人とのみ完全なURLを共有してください。",
    copyLink: "リンクをコピー",
    deleteTripTitle: "この旅行を削除しますか？",
    deleteTripBody:
      "すべての参加者が切断され、サーバーのデータが完全に削除されます。続行するには{title}と入力してください。",
    tripTitleConfirmation: "旅行タイトルの確認",
    showItinerary: "旅程を表示",
    hideItinerary: "旅程を非表示",
    hideItineraryResize: "旅程を非表示。ドラッグまたは矢印キーでサイズを変更できます。",
    start: "開始",
    end: "終了",
    confirmed: "確認済み",
    moveUp: "{title}を上へ移動",
    moveDown: "{title}を下へ移動",
    deleteItem: "{title}を削除",
    updatingRoute: "経路を更新中",
    stale: "未更新",
    routeUnavailable: "経路を利用できません",
    travelMode: "移動手段",
    openLegGoogleMaps: "この経路をGoogleマップで開く",
    openDayGoogleMaps: "この日をGoogleマップで開く",
    showDayRouteOnMap: "{date}のルートを地図に表示",
    dayRouteFewPlaces: "この日をエクスポートするには2か所以上追加してください",
    dayRouteGap: "この日をエクスポートするにはすべての場所を接続してください",
    dayRouteMixedModes: "この日をエクスポートするには移動手段を1つにしてください",
    dayRouteUnavailable: "すべての経路が利用可能になるまでお待ちください",
    deleteDay: "{date}を削除",
    moreItemTypes: "{date}のその他の項目タイプ",
    addItemToDay: "{date}に項目を追加",
    place: "場所",
    note: "メモ",
    reservation: "予約",
    lodging: "宿泊",
    transport: "移動",
    addType: "{type}を追加",
    uiLanguage: "UIの言語",
    tripLanguage: "旅行の言語",
    followUiLanguage: "UIの言語に合わせる（{language}）",
    distanceUnits: "距離の単位",
    metricUnits: "メートル法",
    imperialUnits: "ヤード・ポンド法",
    defaultTransport: "既定の移動手段",
    calendarDayStart: "カレンダーの日の開始時刻",
    saveSettings: "設定を保存",
    discardTripSettings: "保存していない旅行設定を破棄しますか？",
    date: "日付",
    startTime: "開始時刻",
    leaveAt: "出発時刻",
    stayAt: "{title}に滞在",
    checkInDate: "チェックイン日",
    checkOutDate: "チェックアウト日",
    searchGooglePlaces: "Google Placesを検索",
    checkingPlacement: "配置を確認して保存中...",
    choosePlace: "場所を選択してください",
    chooseDateTime: "日付と時刻を選択してください",
    checkoutAfterCheckin: "チェックアウトはチェックインより後にしてください",
    couldNotAddPlace: "この場所を追加できませんでした",
    googlePlacesUnavailable: "Google Placesを利用できません",
    couldNotLoadGooglePlace: "このGoogleの場所を読み込めませんでした",
    somePlacesUnavailable: "一部のGoogleの場所を利用できません",
    placeDetails: "場所の詳細",
    removeFromDay: "{day}日目から削除",
    addToTrip: "旅行に追加",
    closePlaceDetails: "場所の詳細を閉じる",
    loadingPlaceDetails: "場所の詳細を読み込み中...",
    placeDetailsUnavailable: "Googleの場所の詳細を利用できません。",
    retry: "再試行",
    tripMap: "旅行地図",
    mapUnavailable: "地図を利用できません",
    transportLocationsUnavailable: "移動場所を利用できません",
    stopLabel: "{index}番目: {label}",
    selectedPlace: "選択した場所",
    changeField: "{field}を変更",
    removeField: "{field}を削除",
    keepField: "{field}を保持",
    itineraryLabel: "旅程のラベル",
    editLabel: "{title}のラベルを編集",
    changeToReservation: "予約に変更",
    changeToReservationConfirm: "この場所を予約に変更しますか？",
    closeEditor: "エディターを閉じる",
    travelMethod: "移動方法",
    customTravelMethod: "カスタム移動方法",
    from: "出発地",
    to: "目的地",
    departureTime: "出発時刻",
    arrivalTime: "到着時刻",
    durationMinutes: "所要時間（分）",
    notes: "メモ",
    markdownSupported: "Markdown対応",
    edit: "編集",
    preview: "プレビュー",
    stayAfterCheckin: "チェックアウトはチェックインより後にしてください。",
    stayOverlap: "宿泊期間は旅行日程と重なる必要があります。",
    choosePlaceSaving: "保存する前に場所を選択してください。",
    scheduleReservation: "保存する前に予約日を設定してください。",
    chooseStartSaving: "保存する前に開始時刻を選択してください。",
    chooseArrival: "到着時刻を選択してください。",
    provider: "提供元",
    confirmation: "確認番号",
    arrivalDate: "到着日",
    departureDate: "出発日",
    plane: "飛行機",
    train: "電車",
    bus: "バス",
    ferry: "フェリー",
    custom: "カスタム",
    car: "車",
    publicTransport: "公共交通機関",
    walk: "徒歩",
    transportOrigin: "移動の出発地",
    transportDestination: "移動の目的地",
    deleteDayConfirm: "この日を削除しますか？{count}件の項目が「行きたい場所」に移動します。",
    loadingEditor: "エディターを読み込み中",
    nothingToPreview: "プレビューする内容がありません。",
    home: "PaceNotesホーム",
    tripTo: "{place}への旅行",
    invalidLocalTime: "時計の変更により、この現地時刻は存在しないか曖昧です。",
    overlapsItem: "{title}と重なっています。",
    travelCannotFinish: "{title}からの移動はこの開始時刻までに完了できません。",
  },
  "zh-CN": {
    loadingTrip: "正在加载行程",
    syncUnavailable: "同步服务器不可用",
    connectingPlan: "正在连接共享行程",
    placeFallback: "地点",
    deleteDayBlocked: "请先移动或删除预订，然后再删除这一天。",
    tripDatesBlocked: "请移动或删除新行程日期范围之外的预订。",
    tripTitle: "行程标题",
    allSynced: "所有更改均已同步",
    saving: "正在保存更改",
    connecting: "正在连接",
    offline: "离线",
    editorsOnline: "{count} 人在线",
    undo: "撤销",
    redo: "重做",
    tripSettings: "行程设置",
    deleteTrip: "删除行程",
    share: "分享",
    tripDates: "行程日期",
    placesToVisit: "想去的地点",
    plannerView: "规划视图",
    list: "列表",
    map: "地图",
    itinerary: "行程",
    noLodging: "无住宿",
    addPlace: "添加地点",
    addReservation: "添加预订",
    addLodging: "添加住宿",
    calendar: "日历",
    addTransport: "添加交通",
    calendarAddPlace: "添加地点",
    previousDay: "前一天",
    nextDay: "后一天",
    addDayBefore: "在 {date} 前添加一天",
    addDayAfter: "在 {date} 后添加一天",
    earlier15: "提前15分钟",
    later15: "推迟15分钟",
    longer15: "延长15分钟",
    shorter15: "缩短15分钟",
    duplicate: "复制",
    delete: "删除",
    tripCalendar: "行程日历",
    allDay: "全天",
    day: "天",
    days: "天",
    continued: "续",
    flexible: "灵活安排",
    makeFlexible: "设为灵活安排",
    changeCheckIn: "更改 {title} 的入住日期",
    changeCheckOut: "更改 {title} 的退房日期",
    changeStart: "更改 {title} 的开始时间",
    changeEnd: "更改 {title} 的结束时间",
    calendarActions: "{title} 的日历操作",
    calendarAddItem: "添加日历项目",
    conflict: "冲突",
    noItems: "这一天没有项目",
    displayNameTitle: "请输入您的姓名",
    displayNameBody: "此行程中的其他人可以看到您的姓名和在线状态颜色。",
    yourName: "您的姓名",
    continue: "继续",
    cancel: "取消",
    shareTitle: "拥有此链接的任何人都可以编辑",
    shareBody: "此行程没有账户或访问控制。请仅与可以更改或删除行程的人分享完整网址。",
    copyLink: "复制链接",
    deleteTripTitle: "删除此行程？",
    deleteTripBody: "这将断开所有编辑者的连接，并永久删除服务器数据。请输入 {title} 以继续。",
    tripTitleConfirmation: "确认行程标题",
    showItinerary: "显示行程",
    hideItinerary: "隐藏行程",
    hideItineraryResize: "隐藏行程。拖动或使用方向键调整大小。",
    start: "开始",
    end: "结束",
    confirmed: "已确认",
    moveUp: "上移 {title}",
    moveDown: "下移 {title}",
    deleteItem: "删除 {title}",
    updatingRoute: "正在更新路线",
    stale: "未更新",
    routeUnavailable: "路线不可用",
    travelMode: "出行方式",
    openLegGoogleMaps: "在 Google 地图中打开此路线",
    openDayGoogleMaps: "在 Google 地图中打开这一天的路线",
    showDayRouteOnMap: "在地图上显示 {date} 的路线",
    dayRouteFewPlaces: "请至少添加两个地点以导出这一天",
    dayRouteGap: "请连接所有地点以导出这一天",
    dayRouteMixedModes: "请使用一种出行方式以导出这一天",
    dayRouteUnavailable: "请等待所有路线可用",
    deleteDay: "删除 {date}",
    moreItemTypes: "{date} 的更多项目类型",
    addItemToDay: "向 {date} 添加项目",
    place: "地点",
    note: "备注",
    reservation: "预订",
    lodging: "住宿",
    transport: "交通",
    addType: "添加{type}",
    uiLanguage: "界面语言",
    tripLanguage: "行程语言",
    followUiLanguage: "跟随界面语言（{language}）",
    distanceUnits: "距离单位",
    metricUnits: "公制",
    imperialUnits: "英制",
    defaultTransport: "默认交通方式",
    calendarDayStart: "日历日开始时间",
    saveSettings: "保存设置",
    discardTripSettings: "放弃未保存的旅行设置吗？",
    date: "日期",
    startTime: "开始时间",
    leaveAt: "离开时间",
    stayAt: "住在{title}",
    checkInDate: "入住日期",
    checkOutDate: "退房日期",
    searchGooglePlaces: "搜索 Google 地点",
    checkingPlacement: "正在检查位置并保存...",
    choosePlace: "请选择地点",
    chooseDateTime: "请选择日期和时间",
    checkoutAfterCheckin: "退房时间必须晚于入住时间",
    couldNotAddPlace: "无法添加此地点",
    googlePlacesUnavailable: "Google 地点不可用",
    couldNotLoadGooglePlace: "无法加载此 Google 地点",
    somePlacesUnavailable: "部分 Google 地点不可用",
    placeDetails: "地点详情",
    removeFromDay: "从第 {day} 天移除",
    addToTrip: "添加到行程",
    closePlaceDetails: "关闭地点详情",
    loadingPlaceDetails: "正在加载地点详情...",
    placeDetailsUnavailable: "Google 地点详情不可用。",
    retry: "重试",
    tripMap: "行程地图",
    mapUnavailable: "地图不可用",
    transportLocationsUnavailable: "交通地点不可用",
    stopLabel: "第 {index} 站：{label}",
    selectedPlace: "已选择的地点",
    changeField: "更改{field}",
    removeField: "移除{field}",
    keepField: "保留{field}",
    itineraryLabel: "行程标签",
    editLabel: "编辑 {title} 的标签",
    changeToReservation: "更改为预订",
    changeToReservationConfirm: "将此地点更改为预订？",
    closeEditor: "关闭编辑器",
    travelMethod: "交通方式",
    customTravelMethod: "自定义交通方式",
    from: "出发地",
    to: "目的地",
    departureTime: "出发时间",
    arrivalTime: "到达时间",
    durationMinutes: "时长（分钟）",
    notes: "备注",
    markdownSupported: "支持 Markdown",
    edit: "编辑",
    preview: "预览",
    stayAfterCheckin: "退房时间必须晚于入住时间。",
    stayOverlap: "住宿日期必须与行程日期重叠。",
    choosePlaceSaving: "保存前请选择地点。",
    scheduleReservation: "保存前请将此预订安排到某一天。",
    chooseStartSaving: "保存前请选择开始时间。",
    chooseArrival: "请选择到达时间。",
    provider: "服务商",
    confirmation: "确认号",
    arrivalDate: "到达日期",
    departureDate: "离开日期",
    plane: "飞机",
    train: "火车",
    bus: "公交车",
    ferry: "渡轮",
    custom: "自定义",
    car: "驾车",
    publicTransport: "公共交通",
    walk: "步行",
    transportOrigin: "交通起点",
    transportDestination: "交通终点",
    deleteDayConfirm: "删除这一天？{count} 个项目将移至想去的地点。",
    loadingEditor: "正在加载编辑器",
    nothingToPreview: "没有可预览的内容。",
    home: "PaceNotes 首页",
    tripTo: "{place}之旅",
    invalidLocalTime: "由于时钟变更，此本地时间不存在或不明确。",
    overlapsItem: "与 {title} 重叠。",
    travelCannotFinish: "从 {title} 出发的行程无法在此开始时间前完成。",
  },
  "zh-TW": {
    loadingTrip: "正在載入行程",
    syncUnavailable: "同步伺服器無法使用",
    connectingPlan: "正在連線到共享行程",
    placeFallback: "地點",
    deleteDayBlocked: "請先移動或刪除預訂，然後再刪除這一天。",
    tripDatesBlocked: "請移動或刪除新行程日期範圍之外的預訂。",
    tripTitle: "行程標題",
    allSynced: "所有變更均已同步",
    saving: "正在儲存變更",
    connecting: "正在連線",
    offline: "離線",
    editorsOnline: "{count} 人在線上",
    undo: "復原",
    redo: "重做",
    tripSettings: "行程設定",
    deleteTrip: "刪除行程",
    share: "分享",
    tripDates: "行程日期",
    placesToVisit: "想去的地點",
    plannerView: "規劃檢視",
    list: "清單",
    map: "地圖",
    itinerary: "行程",
    noLodging: "無住宿",
    addPlace: "新增地點",
    addReservation: "新增預訂",
    addLodging: "新增住宿",
    calendar: "行事曆",
    addTransport: "新增交通",
    calendarAddPlace: "新增地點",
    previousDay: "前一天",
    nextDay: "後一天",
    addDayBefore: "在 {date} 前新增一天",
    addDayAfter: "在 {date} 後新增一天",
    earlier15: "提前15分鐘",
    later15: "延後15分鐘",
    longer15: "延長15分鐘",
    shorter15: "縮短15分鐘",
    duplicate: "複製",
    delete: "刪除",
    tripCalendar: "行程行事曆",
    allDay: "全天",
    day: "天",
    days: "天",
    continued: "接續",
    flexible: "彈性安排",
    makeFlexible: "設為彈性安排",
    changeCheckIn: "變更 {title} 的入住日期",
    changeCheckOut: "變更 {title} 的退房日期",
    changeStart: "變更 {title} 的開始時間",
    changeEnd: "變更 {title} 的結束時間",
    calendarActions: "{title} 的行事曆操作",
    calendarAddItem: "新增行事曆項目",
    conflict: "衝突",
    noItems: "這一天沒有項目",
    displayNameTitle: "請輸入您的姓名",
    displayNameBody: "此行程中的其他人可以看到您的姓名和在線狀態顏色。",
    yourName: "您的姓名",
    continue: "繼續",
    cancel: "取消",
    shareTitle: "擁有此連結的任何人都可以編輯",
    shareBody: "此行程沒有帳戶或存取控制。請僅與可以變更或刪除行程的人分享完整網址。",
    copyLink: "複製連結",
    deleteTripTitle: "刪除此行程？",
    deleteTripBody: "這將中斷所有編輯者的連線，並永久刪除伺服器資料。請輸入 {title} 以繼續。",
    tripTitleConfirmation: "確認行程標題",
    showItinerary: "顯示行程",
    hideItinerary: "隱藏行程",
    hideItineraryResize: "隱藏行程。拖曳或使用方向鍵調整大小。",
    start: "開始",
    end: "結束",
    confirmed: "已確認",
    moveUp: "上移 {title}",
    moveDown: "下移 {title}",
    deleteItem: "刪除 {title}",
    updatingRoute: "正在更新路線",
    stale: "未更新",
    routeUnavailable: "路線無法使用",
    travelMode: "移動方式",
    openLegGoogleMaps: "在 Google 地圖中開啟此路線",
    openDayGoogleMaps: "在 Google 地圖中開啟這一天的路線",
    showDayRouteOnMap: "在地圖上顯示 {date} 的路線",
    dayRouteFewPlaces: "請至少新增兩個地點以匯出這一天",
    dayRouteGap: "請連接所有地點以匯出這一天",
    dayRouteMixedModes: "請使用一種移動方式以匯出這一天",
    dayRouteUnavailable: "請等待所有路線可用",
    deleteDay: "刪除 {date}",
    moreItemTypes: "{date} 的更多項目類型",
    addItemToDay: "向 {date} 新增項目",
    place: "地點",
    note: "備註",
    reservation: "預訂",
    lodging: "住宿",
    transport: "交通",
    addType: "新增{type}",
    uiLanguage: "介面語言",
    tripLanguage: "行程語言",
    followUiLanguage: "跟隨介面語言（{language}）",
    distanceUnits: "距離單位",
    metricUnits: "公制",
    imperialUnits: "英制",
    defaultTransport: "預設交通方式",
    calendarDayStart: "行事曆日開始時間",
    saveSettings: "儲存設定",
    discardTripSettings: "放棄未儲存的旅行設定嗎？",
    date: "日期",
    startTime: "開始時間",
    leaveAt: "離開時間",
    stayAt: "住在{title}",
    checkInDate: "入住日期",
    checkOutDate: "退房日期",
    searchGooglePlaces: "搜尋 Google 地點",
    checkingPlacement: "正在檢查位置並儲存...",
    choosePlace: "請選擇地點",
    chooseDateTime: "請選擇日期和時間",
    checkoutAfterCheckin: "退房時間必須晚於入住時間",
    couldNotAddPlace: "無法新增此地點",
    googlePlacesUnavailable: "Google 地點無法使用",
    couldNotLoadGooglePlace: "無法載入此 Google 地點",
    somePlacesUnavailable: "部分 Google 地點無法使用",
    placeDetails: "地點詳細資料",
    removeFromDay: "從第 {day} 天移除",
    addToTrip: "新增到行程",
    closePlaceDetails: "關閉地點詳細資料",
    loadingPlaceDetails: "正在載入地點詳細資料...",
    placeDetailsUnavailable: "Google 地點詳細資料無法使用。",
    retry: "重試",
    tripMap: "行程地圖",
    mapUnavailable: "地圖無法使用",
    transportLocationsUnavailable: "交通地點無法使用",
    stopLabel: "第 {index} 站：{label}",
    selectedPlace: "已選擇的地點",
    changeField: "變更{field}",
    removeField: "移除{field}",
    keepField: "保留{field}",
    itineraryLabel: "行程標籤",
    editLabel: "編輯 {title} 的標籤",
    changeToReservation: "變更為預訂",
    changeToReservationConfirm: "將此地點變更為預訂？",
    closeEditor: "關閉編輯器",
    travelMethod: "交通方式",
    customTravelMethod: "自訂交通方式",
    from: "出發地",
    to: "目的地",
    departureTime: "出發時間",
    arrivalTime: "抵達時間",
    durationMinutes: "時長（分鐘）",
    notes: "備註",
    markdownSupported: "支援 Markdown",
    edit: "編輯",
    preview: "預覽",
    stayAfterCheckin: "退房時間必須晚於入住時間。",
    stayOverlap: "住宿日期必須與行程日期重疊。",
    choosePlaceSaving: "儲存前請選擇地點。",
    scheduleReservation: "儲存前請將此預訂安排到某一天。",
    chooseStartSaving: "儲存前請選擇開始時間。",
    chooseArrival: "請選擇抵達時間。",
    provider: "服務商",
    confirmation: "確認號碼",
    arrivalDate: "抵達日期",
    departureDate: "離開日期",
    plane: "飛機",
    train: "火車",
    bus: "公車",
    ferry: "渡輪",
    custom: "自訂",
    car: "開車",
    publicTransport: "大眾運輸",
    walk: "步行",
    transportOrigin: "交通起點",
    transportDestination: "交通終點",
    deleteDayConfirm: "刪除這一天？{count} 個項目將移至想去的地點。",
    loadingEditor: "正在載入編輯器",
    nothingToPreview: "沒有可預覽的內容。",
    home: "PaceNotes 首頁",
    tripTo: "{place}之旅",
    invalidLocalTime: "由於時鐘變更，此本地時間不存在或不明確。",
    overlapsItem: "與 {title} 重疊。",
    travelCannotFinish: "從 {title} 出發的行程無法在此開始時間前完成。",
  },
};

const UiLanguageContext = createContext<TripLanguage>("en");
const TripLanguageContext = createContext<TripLanguage>("en");

export function UiLanguageProvider({
  language,
  children,
}: {
  language: TripLanguage;
  children: ReactNode;
}) {
  useEffect(() => {
    const previous = document.documentElement.lang;
    document.documentElement.lang = languageTag(language);
    return () => {
      document.documentElement.lang = previous;
    };
  }, [language]);
  return <UiLanguageContext value={language}>{children}</UiLanguageContext>;
}

export function TripLanguageProvider({
  language,
  children,
}: {
  language: TripLanguage;
  children: ReactNode;
}) {
  return <TripLanguageContext value={language}>{children}</TripLanguageContext>;
}

export function useUiLanguage(): TripLanguage {
  return useContext(UiLanguageContext);
}

export function useTripLanguage(): TripLanguage {
  return useContext(TripLanguageContext);
}

export function useTripText(): TripText {
  const language = useUiLanguage();
  return useMemo(() => createTripText(language), [language]);
}

export function createTripText(language: TripLanguage): TripText {
  const messages = translations[language];
  return (key, values) => format(messages[key] ?? english[key], values);
}

export function languageTag(language: TripLanguage): string {
  return language;
}
export function formatTravelDuration(totalMinutes: number, language: TripLanguage): string {
  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;
  const formatUnit = (value: number, unit: "hour" | "minute") =>
    new Intl.NumberFormat(languageTag(language), {
      style: "unit",
      unit,
      unitDisplay: "short",
    }).format(value);
  return [hours ? formatUnit(hours, "hour") : "", minutes ? formatUnit(minutes, "minute") : ""]
    .filter(Boolean)
    .join(" ");
}

export function travelModeLabel(language: TripLanguage, mode: TravelMode): string {
  const text = createTripText(language);
  if (mode === "DRIVING") return text("car");
  if (mode === "TRANSIT") return text("publicTransport");
  return text("walk");
}

function format(message: string, values?: Record<string, string | number>): string {
  if (!values) return message;
  return message.replace(/\{(\w+)\}/g, (placeholder, key: string) =>
    Object.hasOwn(values, key) ? String(values[key]) : placeholder,
  );
}
